/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import java.awt.BorderLayout;
import java.io.IOException;
import java.util.logging.Handler;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import komponente.tabela.model.ModelTabeleKlijenti;

/**
 *
 * @author KORISNIK
 */
public class FGlavnaServer extends javax.swing.JFrame {

    private ModelTabeleKlijenti model;
    Logger logger = Logger.getLogger("MyLog");

    /**
     * Creates new form FGlavnaServer
     */
    public FGlavnaServer(ModelTabeleKlijenti model) {
        initComponents();
        this.model = model;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuServer = new javax.swing.JMenu();
        jMenuItemKonfiguracijaServera = new javax.swing.JMenuItem();
        jMenuBaza = new javax.swing.JMenu();
        jMenuItemKonfiguracijaiBaze = new javax.swing.JMenuItem();
        jMenuKlijenti = new javax.swing.JMenu();
        jMenuItemAktivniKlijenti = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Server kladionica");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jMenuServer.setText("Server");

        jMenuItemKonfiguracijaServera.setText("Konfiguracija servera");
        jMenuItemKonfiguracijaServera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemKonfiguracijaServeraActionPerformed(evt);
            }
        });
        jMenuServer.add(jMenuItemKonfiguracijaServera);

        jMenuBar1.add(jMenuServer);

        jMenuBaza.setText("Baza");

        jMenuItemKonfiguracijaiBaze.setText("Konfiguracija baze");
        jMenuItemKonfiguracijaiBaze.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemKonfiguracijaiBazeActionPerformed(evt);
            }
        });
        jMenuBaza.add(jMenuItemKonfiguracijaiBaze);

        jMenuBar1.add(jMenuBaza);

        jMenuKlijenti.setText("Klijenti");

        jMenuItemAktivniKlijenti.setText("Aktivni klijenti");
        jMenuItemAktivniKlijenti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAktivniKlijentiActionPerformed(evt);
            }
        });
        jMenuKlijenti.add(jMenuItemAktivniKlijenti);

        jMenuBar1.add(jMenuKlijenti);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 485, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 333, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemKonfiguracijaiBazeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemKonfiguracijaiBazeActionPerformed
        // TODO add your handling code here:
        JFrame fGlavna = this;
        int stanje = fGlavna.getExtendedState();
        fGlavna.getContentPane().removeAll();

        JPanelBaza jPanel = null;

        try {
            jPanel = new JPanelBaza();
        } catch (IOException ex) {
            Logger.getLogger(FGlavnaServer.class.getName()).log(Level.SEVERE, null, ex);
        }

        JScrollPane jScroll = new JScrollPane(jPanel);

        fGlavna.add(jScroll, BorderLayout.CENTER);

        fGlavna.pack();


    }//GEN-LAST:event_jMenuItemKonfiguracijaiBazeActionPerformed

    private void jMenuItemKonfiguracijaServeraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemKonfiguracijaServeraActionPerformed
        try {
            JFrame fGlavna = this;
            int stanje = fGlavna.getExtendedState();
            fGlavna.getContentPane().removeAll();

            JPanelServer jPanel = null;

            jPanel = new JPanelServer(model);

            JScrollPane jScroll = new JScrollPane(jPanel);

            fGlavna.add(jScroll, BorderLayout.CENTER);

            fGlavna.pack();

        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Doslo je do greske prilikom ucitavanja default porta!");
        }

    }//GEN-LAST:event_jMenuItemKonfiguracijaServeraActionPerformed

    private void jMenuItemAktivniKlijentiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAktivniKlijentiActionPerformed
        // TODO add your handling code here:
        JFrame fGlavna = this;
        int stanje = fGlavna.getExtendedState();
        fGlavna.getContentPane().removeAll();

        JPanelKlijenti jPanel = null;

        jPanel = new JPanelKlijenti(model);

        JScrollPane jScroll = new JScrollPane(jPanel);
        fGlavna.add(jScroll, BorderLayout.CENTER);

        fGlavna.pack();
    }//GEN-LAST:event_jMenuItemAktivniKlijentiActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        zatvoriHandlere();
    }//GEN-LAST:event_formWindowClosing
    private void zatvoriHandlere() {
        for (Handler h : logger.getHandlers()) {
            h.close();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuBaza;
    private javax.swing.JMenuItem jMenuItemAktivniKlijenti;
    private javax.swing.JMenuItem jMenuItemKonfiguracijaServera;
    private javax.swing.JMenuItem jMenuItemKonfiguracijaiBaze;
    private javax.swing.JMenu jMenuKlijenti;
    private javax.swing.JMenu jMenuServer;
    // End of variables declaration//GEN-END:variables
}
