/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.util.Properties;
import javax.swing.JOptionPane;

/**
 *
 * @author KORISNIK
 */
public class JPanelBaza extends javax.swing.JPanel {

    private File file = new File("config.properties");
    private Properties configProperty;

    /**
     * Creates new form JPanelBaza
     */
    public JPanelBaza() throws IOException {
        initComponents();

        jButtonZapamtiParametre.setEnabled(false);

        jButtonPromeniParametre.setVisible(false);

        ucitajVrednostiZaBazu();

        jTextFieldUrl.setText(configProperty.getProperty("url"));
        jTextFieldUsername.setText(configProperty.getProperty("user"));
        jPasswordField.setText(configProperty.getProperty("password"));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldUrl = new javax.swing.JTextField();
        jTextFieldUsername = new javax.swing.JTextField();
        jPasswordField = new javax.swing.JPasswordField();
        jButtonTestirajKonekciju = new javax.swing.JButton();
        jButtonZapamtiParametre = new javax.swing.JButton();
        jButtonPromeniParametre = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("URL:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Username:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Password:");

        jTextFieldUrl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jTextFieldUsername.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUsernameActionPerformed(evt);
            }
        });

        jPasswordField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jButtonTestirajKonekciju.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonTestirajKonekciju.setText("Testiraj konekciju");
        jButtonTestirajKonekciju.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTestirajKonekcijuActionPerformed(evt);
            }
        });

        jButtonZapamtiParametre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonZapamtiParametre.setText("Zapamti parametre");
        jButtonZapamtiParametre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonZapamtiParametreActionPerformed(evt);
            }
        });

        jButtonPromeniParametre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonPromeniParametre.setText("Promeni parametre");
        jButtonPromeniParametre.setEnabled(false);
        jButtonPromeniParametre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPromeniParametreActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jPasswordField, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                                .addComponent(jTextFieldUsername))
                            .addComponent(jTextFieldUrl, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonPromeniParametre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonTestirajKonekciju, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(15, 15, 15)
                        .addComponent(jButtonZapamtiParametre)))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldUrl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonPromeniParametre)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonTestirajKonekciju)
                    .addComponent(jButtonZapamtiParametre))
                .addContainerGap(81, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUsernameActionPerformed

    private void jButtonZapamtiParametreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonZapamtiParametreActionPerformed
        // TODO add your handling code here:
        int odg = JOptionPane.showConfirmDialog(this, "Da li ste sigurni da hocete da zapamtite parametre?");
        if (odg == 0) {
            configProperty.setProperty("url", jTextFieldUrl.getText().trim());

            configProperty.setProperty("user", jTextFieldUsername.getText().trim());
            configProperty.setProperty("password", jPasswordField.getText().trim());
            OutputStream outputStream;
            try {
                outputStream = new FileOutputStream(file);
                configProperty.store(outputStream, null);
                outputStream.close();
                JOptionPane.showMessageDialog(this, "Parametri su uspesno zapamceni!");

                jTextFieldUrl.setEnabled(true);
                jTextFieldUsername.setEnabled(true);
                jPasswordField.setEnabled(true);

                jButtonZapamtiParametre.setEnabled(false);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Desila se greska prilikom pamcenja parametara!");
            }
        }

    }//GEN-LAST:event_jButtonZapamtiParametreActionPerformed

    private void jButtonTestirajKonekcijuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTestirajKonekcijuActionPerformed
        // TODO add your handling code here:

        String url = jTextFieldUrl.getText().trim();
        String user = jTextFieldUsername.getText().trim();
        String pass = jPasswordField.getText().trim();
        try {

            Connection konekcija;
            konekcija = DriverManager.getConnection(url, user, pass);

            konekcija.close();

            JOptionPane.showMessageDialog(this, "Konekcija je uspesno testirana!");

            jButtonZapamtiParametre.setEnabled(true);

            jTextFieldUrl.setEnabled(false);
            jTextFieldUsername.setEnabled(false);
            jPasswordField.setEnabled(false);

            jButtonPromeniParametre.setEnabled(true);
            jButtonPromeniParametre.setVisible(true);
        } catch (Exception e) {

            JOptionPane.showMessageDialog(this, "Desila se greska prilikom testiranja konekcije!");
        }
    }//GEN-LAST:event_jButtonTestirajKonekcijuActionPerformed

    private void jButtonPromeniParametreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPromeniParametreActionPerformed
        // TODO add your handling code here:
        jTextFieldUrl.setEnabled(true);
        jTextFieldUsername.setEnabled(true);
        jPasswordField.setEnabled(true);

        jButtonZapamtiParametre.setEnabled(false);
    }//GEN-LAST:event_jButtonPromeniParametreActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonPromeniParametre;
    private javax.swing.JButton jButtonTestirajKonekciju;
    private javax.swing.JButton jButtonZapamtiParametre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField jPasswordField;
    private javax.swing.JTextField jTextFieldUrl;
    private javax.swing.JTextField jTextFieldUsername;
    // End of variables declaration//GEN-END:variables

    private void ucitajVrednostiZaBazu() throws FileNotFoundException, IOException {

        Properties dp = new Properties();

        dp.setProperty("url", "jdbc:mysql://localhost:3306/kladionica");
        dp.setProperty("user", "root");
        dp.setProperty("password", "");

        configProperty = new Properties(dp);

    }
}
